In [3]:
import numpy as np
import pandas as pd
import os
import glob

# Reading csv files and concat them to one single pandas data frame

In [10]:
path = r'/Users/behdad/Learning/TwitterBot/Tweepy_Twitter_Scraper/' # use your path
all_files = glob.glob(path + "/*.csv")

li = []

for filename in all_files:
    df = pd.read_csv(filename , encoding='utf-8')
    li.append(df)

dataframe = pd.concat(li, axis=0, ignore_index=True)

In [11]:
dataframe.shape

(21047, 15)

In [15]:
dataframe.head()

,Unnamed: 0,Datetime,Tweet Id,Text,retweet_count,favorite_count,entities,tweet_source,user_screenname,user_name,location,user_description,user_followers,user_friends,user_create_account
0,0,2020-02-06 09:29:10,1225350710935638016,@samousavia میلی‌لیتر,0,2,"{'hashtags': [], 'symbols': [], 'user_mentions...",Twitter for Android,1alpr,علی پیرحسین‌لو,NaN,NaN,5123,683,2010-07-30 07:11:14
1,1,2020-02-05 09:37:26,1224990403780280320,RT @Majid6359: #سناتور_مکنزی وزیر کشاورزی و وز...,3,0,"{'hashtags': [{'text': 'سناتور_مکنزی', 'indice...",Twitter for Android,1alpr,علی پیرحسین‌لو,NaN,NaN,5123,683,2010-07-30 07:11:14
2,2,2020-02-05 09:27:28,1224987896668721152,@omidhosseini80 ما گول نمی‌خوریم. یه عمریه هر ...,0,2,"{'hashtags': [], 'symbols': [], 'user_mentions...",Twitter for Android,1alpr,علی پیرحسین‌لو,NaN,NaN,5123,683,2010-07-30 07:11:14
3,3,2020-02-05 09:08:08,1224983029799694339,@omidhosseini80 یه آخوند بی‌عمامه دیدم. داشتم ...,0,1,"{'hashtags': [], 'symbols': [], 'user_mentions...",Twitter for Android,1alpr,علی پیرحسین‌لو,NaN,NaN,5123,683,2010-07-30 07:11:14
4,4,2020-02-05 09:06:08,1224982527112351745,@omidhosseini80 آخوند چرا نداره! یعنی میرن؟,0,5,"{'hashtags': [], 'symbols': [], 'user_mentions...",Twitter for Android,1alpr,علی پیرحسین‌لو,NaN,NaN,5123,683,2010-07-30 07:11:14

In [16]:
dataframe.tail()

,Unnamed: 0,Datetime,Tweet Id,Text,retweet_count,favorite_count,entities,tweet_source,user_screenname,user_name,location,user_description,user_followers,user_friends,user_create_account
21042,195,2018-11-06 09:52:41,1059745377551872000,مرثیه ی پیام رسان های داخلی،حاکی از ضعف مفرط ت...,42,736,"{'hashtags': [], 'symbols': [], 'user_mentions...",Twitter Web Client,Zarghami_ez,سید عزت الله ضرغامی,Islamic Republic of Iran,عضو شورایعالی انقلاب فرهنگی\nعضو شورایعالی فضا...,97682,27,2016-08-16 11:46:38
21043,196,2018-11-03 14:13:58,1058723965068283905,اعتقاد برخی سیاستمداران به ضرورت مذاکره با آمر...,27,196,"{'hashtags': [{'text': 'دوقطبی', 'indices': [9...",Twitter Web Client,Zarghami_ez,سید عزت الله ضرغامی,Islamic Republic of Iran,عضو شورایعالی انقلاب فرهنگی\nعضو شورایعالی فضا...,97682,27,2016-08-16 11:46:38
21044,197,2018-10-25 16:50:10,1055501786277134337,همه می‌دانستند که نقد کردن صد هزار دینار ناقاب...,300,2405,"{'hashtags': [], 'symbols': [], 'user_mentions...",Twitter for Android,Zarghami_ez,سید عزت الله ضرغامی,Islamic Republic of Iran,عضو شورایعالی انقلاب فرهنگی\nعضو شورایعالی فضا...,97682,27,2016-08-16 11:46:38
21045,198,2018-10-21 10:24:03,1053955064727953408,ضرغامی در گفتگو با ایرنا، درباره علت هشدار اخی...,21,277,"{'hashtags': [{'text': 'آقایان', 'indices': [1...",Twitter for Android,Zarghami_ez,سید عزت الله ضرغامی,Islamic Republic of Iran,عضو شورایعالی انقلاب فرهنگی\nعضو شورایعالی فضا...,97682,27,2016-08-16 11:46:38
21046,199,2018-10-19 14:35:25,1053293548731158528,نمی‌خواهیم مردم را به زور به بهشت ببریم.\n ولی...,107,1517,"{'hashtags': [], 'symbols': [], 'user_mentions...",Twitter for Android,Zarghami_ez,سید عزت الله ضرغامی,Islamic Republic of Iran,عضو شورایعالی انقلاب فرهنگی\nعضو شورایعالی فضا...,97682,27,2016-08-16 11:46:38

In [14]:
dataframe.to_csv('political_tweets.csv', header=True,encoding='utf-8')

In [56]:
dataframe.dtypes

Unnamed: 0                      int64
Datetime               datetime64[ns]
Tweet Id                        int64
Text                           object
retweet_count                   int64
favorite_count                  int64
entities                       object
tweet_source                   object
user_screenname                object
user_name                      object
location                       object
user_description               object
user_followers                  int64
user_friends                    int64
user_create_account    datetime64[ns]
tweet_date             datetime64[ns]
tweet_time                     object
dtype: object

In [30]:
dataframe.columns

Index(['Unnamed: 0', 'Datetime', 'Tweet Id', 'Text', 'retweet_count',
       'favorite_count', 'entities', 'tweet_source', 'user_screenname',
       'user_name', 'location', 'user_description', 'user_followers',
       'user_friends', 'user_create_account'],
      dtype='object')

In [32]:
dataframe['Datetime'] = pd.to_datetime(dataframe['Datetime'])

dataframe['tweet_date'] = [d.date() for d in dataframe['Datetime']]
dataframe['tweet_time'] = [d.time() for d in dataframe['Datetime']]

In [57]:
dataframe.dtypes

Unnamed: 0                      int64
Datetime               datetime64[ns]
Tweet Id                        int64
Text                           object
retweet_count                   int64
favorite_count                  int64
entities                       object
tweet_source                   object
user_screenname                object
user_name                      object
location                       object
user_description               object
user_followers                  int64
user_friends                    int64
user_create_account    datetime64[ns]
tweet_date             datetime64[ns]
tweet_time                     object
dtype: object

In [39]:
dataframe['tweet_date']=dataframe['tweet_date'].astype('datetime64[ns]')
dataframe['user_create_account']=dataframe['user_create_account'].astype('datetime64[ns]')

dataframe.dtypes

Unnamed: 0                      int64
Datetime               datetime64[ns]
Tweet Id                        int64
Text                           object
retweet_count                   int64
favorite_count                  int64
entities                       object
tweet_source                   object
user_screenname                object
user_name                      object
location                       object
user_description               object
user_followers                  int64
user_friends                    int64
user_create_account    datetime64[ns]
tweet_date             datetime64[ns]
tweet_time                     object
dtype: object

In [71]:
dataframe.columns

Index(['Datetime', 'Tweet Id', 'Text', 'retweet_count', 'favorite_count',
       'entities', 'tweet_source', 'user_screenname', 'user_name', 'location',
       'user_description', 'user_followers', 'user_friends',
       'user_create_account', 'tweet_date', 'tweet_time'],
      dtype='object')

In [80]:
dataframe

,Datetime,Tweet Id,Text,retweet_count,favorite_count,entities,tweet_source,user_screenname,user_name,location,user_description,user_followers,user_friends,user_create_account,tweet_date,tweet_time
0,2020-02-06 09:29:10,1225350710935638016,@samousavia میلی‌لیتر,0,2,"{'hashtags': [], 'symbols': [], 'user_mentions...",Twitter for Android,1alpr,علی پیرحسین‌لو,NaN,NaN,5123,683,2010-07-30 07:11:14,2020-02-06,09:29:10
1,2020-02-05 09:37:26,1224990403780280320,RT @Majid6359: #سناتور_مکنزی وزیر کشاورزی و وز...,3,0,"{'hashtags': [{'text': 'سناتور_مکنزی', 'indice...",Twitter for Android,1alpr,علی پیرحسین‌لو,NaN,NaN,5123,683,2010-07-30 07:11:14,2020-02-05,09:37:26
2,2020-02-05 09:27:28,1224987896668721152,@omidhosseini80 ما گول نمی‌خوریم. یه عمریه هر ...,0,2,"{'hashtags': [], 'symbols': [], 'user_mentions...",Twitter for Android,1alpr,علی پیرحسین‌لو,NaN,NaN,5123,683,2010-07-30 07:11:14,2020-02-05,09:27:28
3,2020-02-05 09:08:08,1224983029799694339,@omidhosseini80 یه آخوند بی‌عمامه دیدم. داشتم ...,0,1,"{'hashtags': [], 'symbols': [], 'user_mentions...",Twitter for Android,1alpr,علی پیرحسین‌لو,NaN,NaN,5123,683,2010-07-30 07:11:14,2020-02-05,09:08:08
4,2020-02-05 09:06:08,1224982527112351745,@omidhosseini80 آخوند چرا نداره! یعنی میرن؟,0,5,"{'hashtags': [], 'symbols': [], 'user_mentions...",Twitter for Android,1alpr,علی پیرحسین‌لو,NaN,NaN,5123,683,2010-07-30 07:11:14,2020-02-05,09:06:08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21042,2018-11-06 09:52:41,1059745377551872000,مرثیه ی پیام رسان های داخلی،حاکی از ضعف مفرط ت...,42,736,"{'hashtags': [], 'symbols': [], 'user_mentions...",Twitter Web Client,Zarghami_ez,سید عزت الله ضرغامی,Islamic Republic of Iran,عضو شورایعالی انقلاب فرهنگی\nعضو شورایعالی فضا...,97682,27,2016-08-16 11:46:38,2018-11-06,09:52:41
21043,2018-11-03 14:13:58,1058723965068283905,اعتقاد برخی سیاستمداران به ضرورت مذاکره با آمر...,27,196,"{'hashtags': [{'text': 'دوقطبی', 'indices': [9...",Twitter Web Client,Zarghami_ez,سید عزت الله ضرغامی,Islamic Republic of Iran,عضو شورایعالی انقلاب فرهنگی\nعضو شورایعالی فضا...,97682,27,2016-08-16 11:46:38,2018-11-03,14:13:58
21044,2018-10-25 16:50:10,1055501786277134337,همه می‌دانستند که نقد کردن صد هزار دینار ناقاب...,300,2405,"{'hashtags': [], 'symbols': [], 'user_mentions...",Twitter for Android,Zarghami_ez,سید عزت الله ضرغامی,Islamic Republic of Iran,عضو شورایعالی انقلاب فرهنگی\nعضو شورایعالی فضا...,97682,27,2016-08-16 11:46:38,2018-10-25,16:50:10
21045,2018-10-21 10:24:03,1053955064727953408,ضرغامی در گفتگو با ایرنا، درباره علت هشدار اخی...,21,277,"{'hashtags': [{'text': 'آقایان', 'indices': [1...",Twitter for Android,Zarghami_ez,سید عزت الله ضرغامی,Islamic Republic of Iran,عضو شورایعالی انقلاب فرهنگی\nعضو شورایعالی فضا...,97682,27,2016-08-16 11:46:38,2018-10-21,10:24:03
21046,2018-10-19 14:35:25,1053293548731158528,نمی‌خواهیم مردم را به زور به بهشت ببریم.\n ولی...,107,1517,"{'hashtags': [], 'symbols': [], 'user_mentions...",Twitter for Android,Zarghami_ez,سید عزت الله ضرغامی,Islamic Republic of Iran,عضو شورایعالی انقلاب فرهنگی\nعضو شورایعالی فضا...,97682,27,2016-08-16 11:46:38,2018-10-19,14:35:25

In [73]:
# dataframe.to_csv('political_tweets_v2.csv', header=True,encoding='utf-8')

df= pd.read_csv('political_tweets_v2.csv', )

In [74]:
df

,Unnamed: 0,Datetime,Tweet Id,Text,retweet_count,favorite_count,entities,tweet_source,user_screenname,user_name,location,user_description,user_followers,user_friends,user_create_account,tweet_date,tweet_time
0,0,2020-02-06 09:29:10,1225350710935638016,@samousavia میلی‌لیتر,0,2,"{'hashtags': [], 'symbols': [], 'user_mentions...",Twitter for Android,1alpr,علی پیرحسین‌لو,NaN,NaN,5123,683,2010-07-30 07:11:14,2020-02-06 00:00:00,09:29:10
1,1,2020-02-05 09:37:26,1224990403780280320,RT @Majid6359: #سناتور_مکنزی وزیر کشاورزی و وز...,3,0,"{'hashtags': [{'text': 'سناتور_مکنزی', 'indice...",Twitter for Android,1alpr,علی پیرحسین‌لو,NaN,NaN,5123,683,2010-07-30 07:11:14,2020-02-05 00:00:00,09:37:26
2,2,2020-02-05 09:27:28,1224987896668721152,@omidhosseini80 ما گول نمی‌خوریم. یه عمریه هر ...,0,2,"{'hashtags': [], 'symbols': [], 'user_mentions...",Twitter for Android,1alpr,علی پیرحسین‌لو,NaN,NaN,5123,683,2010-07-30 07:11:14,2020-02-05 00:00:00,09:27:28
3,3,2020-02-05 09:08:08,1224983029799694339,@omidhosseini80 یه آخوند بی‌عمامه دیدم. داشتم ...,0,1,"{'hashtags': [], 'symbols': [], 'user_mentions...",Twitter for Android,1alpr,علی پیرحسین‌لو,NaN,NaN,5123,683,2010-07-30 07:11:14,2020-02-05 00:00:00,09:08:08
4,4,2020-02-05 09:06:08,1224982527112351745,@omidhosseini80 آخوند چرا نداره! یعنی میرن؟,0,5,"{'hashtags': [], 'symbols': [], 'user_mentions...",Twitter for Android,1alpr,علی پیرحسین‌لو,NaN,NaN,5123,683,2010-07-30 07:11:14,2020-02-05 00:00:00,09:06:08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21042,21042,2018-11-06 09:52:41,1059745377551872000,مرثیه ی پیام رسان های داخلی،حاکی از ضعف مفرط ت...,42,736,"{'hashtags': [], 'symbols': [], 'user_mentions...",Twitter Web Client,Zarghami_ez,سید عزت الله ضرغامی,Islamic Republic of Iran,عضو شورایعالی انقلاب فرهنگی\nعضو شورایعالی فضا...,97682,27,2016-08-16 11:46:38,2018-11-06 00:00:00,09:52:41
21043,21043,2018-11-03 14:13:58,1058723965068283905,اعتقاد برخی سیاستمداران به ضرورت مذاکره با آمر...,27,196,"{'hashtags': [{'text': 'دوقطبی', 'indices': [9...",Twitter Web Client,Zarghami_ez,سید عزت الله ضرغامی,Islamic Republic of Iran,عضو شورایعالی انقلاب فرهنگی\nعضو شورایعالی فضا...,97682,27,2016-08-16 11:46:38,2018-11-03 00:00:00,14:13:58
21044,21044,2018-10-25 16:50:10,1055501786277134337,همه می‌دانستند که نقد کردن صد هزار دینار ناقاب...,300,2405,"{'hashtags': [], 'symbols': [], 'user_mentions...",Twitter for Android,Zarghami_ez,سید عزت الله ضرغامی,Islamic Republic of Iran,عضو شورایعالی انقلاب فرهنگی\nعضو شورایعالی فضا...,97682,27,2016-08-16 11:46:38,2018-10-25 00:00:00,16:50:10
21045,21045,2018-10-21 10:24:03,1053955064727953408,ضرغامی در گفتگو با ایرنا، درباره علت هشدار اخی...,21,277,"{'hashtags': [{'text': 'آقایان', 'indices': [1...",Twitter for Android,Zarghami_ez,سید عزت الله ضرغامی,Islamic Republic of Iran,عضو شورایعالی انقلاب فرهنگی\nعضو شورایعالی فضا...,97682,27,2016-08-16 11:46:38,2018-10-21 00:00:00,10:24:03
21046,21046,2018-10-19 14:35:25,1053293548731158528,نمی‌خواهیم مردم را به زور به بهشت ببریم.\n ولی...,107,1517,"{'hashtags': [], 'symbols': [], 'user_mentions...",Twitter for Android,Zarghami_ez,سید عزت الله ضرغامی,Islamic Republic of Iran,عضو شورایعالی انقلاب فرهنگی\nعضو شورایعالی فضا...,97682,27,2016-08-16 11:46:38,2018-10-19 00:00:00,14:35:25

In [76]:
del df['Unnamed: 0']

In [77]:
df.dtypes

Datetime               object
Tweet Id                int64
Text                   object
retweet_count           int64
favorite_count          int64
entities               object
tweet_source           object
user_screenname        object
user_name              object
location               object
user_description       object
user_followers          int64
user_friends            int64
user_create_account    object
tweet_date             object
tweet_time             object
dtype: object

In [81]:
dataframe['tweet_date']=dataframe['tweet_date'].astype('datetime64[ns]')
dataframe['user_create_account']=dataframe['user_create_account'].astype('datetime64[ns]')

dataframe.dtypes

Datetime               datetime64[ns]
Tweet Id                        int64
Text                           object
retweet_count                   int64
favorite_count                  int64
entities                       object
tweet_source                   object
user_screenname                object
user_name                      object
location                       object
user_description               object
user_followers                  int64
user_friends                    int64
user_create_account    datetime64[ns]
tweet_date             datetime64[ns]
tweet_time                     object
dtype: object

In [82]:
df.describe(include = "all")

,Datetime,Tweet Id,Text,retweet_count,favorite_count,entities,tweet_source,user_screenname,user_name,location,user_description,user_followers,user_friends,user_create_account,tweet_date,tweet_time
count,21047,2.104700e+04,21047,21047.000000,21047.000000,21047,21047,21047,21047,17170,20138,2.104700e+04,21047.000000,21047,21047,21047
unique,20713,NaN,20838,NaN,NaN,18557,18,143,143,32,137,NaN,NaN,143,1353,17759
top,2020-01-20 06:05:07,NaN,@hesamodllin1 حساب کاربری@hesamodllin1 جعلی است.,NaN,NaN,"{'hashtags': [], 'symbols': [], 'user_mentions...",Twitter for iPhone,Alirabiei_ir,دکتر محمود احمدی نژاد,Islamic Republic of Iran,زهرا نژادبهرام\n#عضو_شورای_شهر_تهران\nمتولد ۱۳...,NaN,NaN,2017-10-11 19:32:00,2020-01-03 00:00:00,15:58:34
freq,4,NaN,14,NaN,NaN,1040,8827,200,200,7609,200,NaN,NaN,200,208,5
mean,NaN,1.087622e+18,NaN,102.369364,372.858840,NaN,NaN,NaN,NaN,NaN,NaN,5.935738e+04,144.715541,NaN,NaN,NaN
std,NaN,1.294495e+17,NaN,1266.244751,1306.696894,NaN,NaN,NaN,NaN,NaN,NaN,1.794744e+05,344.899504,NaN,NaN,NaN
min,NaN,2.842295e+17,NaN,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,1.240000e+02,0.000000,NaN,NaN,NaN
25%,NaN,1.027833e+18,NaN,0.000000,3.000000,NaN,NaN,NaN,NaN,NaN,NaN,3.566000e+03,17.000000,NaN,NaN,NaN
50%,NaN,1.117935e+18,NaN,4.000000,31.000000,NaN,NaN,NaN,NaN,NaN,NaN,1.163000e+04,60.000000,NaN,NaN,NaN
75%,NaN,1.192533e+18,NaN,25.000000,180.000000,NaN,NaN,NaN,NaN,NaN,NaN,2.791400e+04,133.000000,NaN,NaN,NaN
max,NaN,1.226423e+18,NaN,126700.000000,55378.000000,NaN,NaN,NaN,NaN,NaN,NaN,1.512252e+06,3246.000000,NaN,NaN,NaN

In [84]:
missing_data = df.isnull()
missing_data.head()

,Datetime,Tweet Id,Text,retweet_count,favorite_count,entities,tweet_source,user_screenname,user_name,location,user_description,user_followers,user_friends,user_create_account,tweet_date,tweet_time
0,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False

In [85]:
for column in missing_data.columns.values.tolist():
    print("\n")
    print(column)
    print(missing_data[column].value_counts())

Datetime
False    21047
Name: Datetime, dtype: int64


Tweet Id
False    21047
Name: Tweet Id, dtype: int64


Text
False    21047
Name: Text, dtype: int64


retweet_count
False    21047
Name: retweet_count, dtype: int64


favorite_count
False    21047
Name: favorite_count, dtype: int64


entities
False    21047
Name: entities, dtype: int64


tweet_source
False    21047
Name: tweet_source, dtype: int64


user_screenname
False    21047
Name: user_screenname, dtype: int64


user_name
False    21047
Name: user_name, dtype: int64


location
False    17170
True      3877
Name: location, dtype: int64


user_description
False    20138
True       909
Name: user_description, dtype: int64


user_followers
False    21047
Name: user_followers, dtype: int64


user_friends
False    21047
Name: user_friends, dtype: int64


user_create_account
False    21047
Name: user_create_account, dtype: int64


tweet_date
False    21047
Name: tweet_date, dtype: int64


tweet_time
False    21047
Name: tweet_time, dtype: int64

In [86]:
df['user_screenname'].value_counts()

Alirabiei_ir      200
DrSaeedJalili     200
S_A_Salehi        200
HasankarimiG      200
mah_sadeghi       200
                 ...
HassanNooroozi     12
BijanZanganeh       4
rezarahmanii        3
MMirlohii           1
yagob_shivyari      1
Name: user_screenname, Length: 143, dtype: int64

In [87]:
df['user_screenname'].unique()

array(['1alpr', 'AfshinHabibzade', 'ahadazadikhah', 'ahmadamirabadi1',
       'ahmadhematii', 'Ahmadinejad1956', 'Ahmadinejad_fa',
       'Ahmadkhatami_ir', 'AK_Hosseinzadeh', 'alia_peyvandi',
       'AliEtaMedia', 'alimotahari_ir', 'AliNajafi_ir', 'Alirabiei_ir',
       'alirezaghanadan', 'AliSari1397', 'alishakourirad', 'AMasjedjamei',
       'aminimedia_ir', 'amirnazemy', 'araghchi', 'ArvinBahare',
       'ar_moezi', 'AshrafBrujerdi', 'azarijahromi', 'Azizjafaari_ir',
       'a_rahimi_mp', 'A_Yarmohammadi', 'Badamchi_Media', 'baeidinejad',
       'barari_ir', 'BijanZanganeh', 'Dastjerdi_ir', 'DrAboutalebi',
       'Drjalilrahimi', 'drmdehghan', 'DrSaeedJalili', 'Dr_Vaezi',
       'ebtekarm_ir', 'ElhamFakhari', 'elyashazrati', 'Eshaq_jahangiri',
       'EsmaeiliParviz', 'farahani52', 'Fassih_F', 'fatahi_ir',
       'fazelmaybodi', 'ghasemsoleimane', 'Ghheidari', 'HaddadAdel_ir',
       'HadiKhaniki', 'HajiDeligani', 'hajmajid47', 'HaniyehSamei',
       'HasankarimiG', 'hasanrasouli', 'HassanKhomeini', 'HassanNooroozi',
       'hesamodin1', 'HKhalilAbadi', 'Hn_jalali', 'hojatmirzaei',
       'hojjat_nazari', 'homayonhashemi', 'hoseinipouya',
       'HoseinNaghashi', 'IRIMFA', 'ir_aref', 'ir_rezaee',
       'Jafarzadeh_ir', 'jalali_kazem', 'jamshid_ansari', 'JZarif',
       'j_mohebinia', 'kabiri_mj', 'kabi_abbas', 'Kadkhodaee_ir',
       'Khamenei_fa', 'khamenei_ir', 'Khatamimedia', 'Khojasteh_ir',
       'kolivand98', 'k_karampour', 'mahdi_sheykh', 'mahkiaee',
       'mah_sadeghi', 'mazaniahmad', 'mb_ghalibaf', 'MB_Nobakht',
       'mehdi_mahdavian', 'mesbahyazdi_ir', 'milani_arash',
       'mirmeysamasad', 'MjHaghshenas', 'mjnanakar', 'MMirlohii',
       'mohsenmirdamadi', 'moh_rafsanjani', 'mounesan_ir', 'mowlaverdi',
       'msoltanifar_ir', 'Nahavandian_ir', 'Nahid_Tajedin',
       'NiknamSepanta', 'N_Khodakarami', 'oladghobad_f', 'Panahian_IR',
       'ParsaeiB', 'ParvanehMafi', 'pirouzhanachi', 'P_Salahshouri',
       'Qarati_ir', 'rafsanjani_fa', 'rezarahmanii', 'Rouhani_ir',
       'RVahidianS', 'sadjadb', 'sadrazamnouri', 'saeidiftm',
       'salari_mohamad', 'seyedmajidsadr2', 'sfaridmousavi',
       'Shahin_Arpanahi', 'shahla_osouli', 'shariatmadari_m',
       'shirankhorasani', 'shohre_naseri', 'shrbamani', 'sm_bathaei',
       'SoroushAbolfazl', 'S_A_Salehi', 'S_FatemeHoseini',
       'TayebehSiavash', 'tondgouyan', 'torabianIR', 'v_seif',
       'yagob_shivyari', 'yousefnejad_ir', 'Zahedi_ir', 'ZahraAhmadipour',
       'zahrasaei_ir', 'zahra_nezhad', 'Zarghami_ez'], dtype=object)

In [89]:
print('number of account: ' , len(df['user_screenname'].unique()))

number of account:  143

In [96]:
df['tweet_date']=df['tweet_date'].astype('datetime64[ns]')
monthly_df = df.groupby([df['tweet_date'].dt.year.rename('year'), df['tweet_date'].dt.month.rename('month')]).agg({'count'})
# monthly_df.hist()

monthly_df

           Datetime Tweet Id  Text retweet_count favorite_count entities  \
              count    count count         count          count    count
year month
2012 12           6        6     6             6              6        6
2013 1           21       21    21            21             21       21
     2            5        5     5             5              5        5
     11           7        7     7             7              7        7
     12           6        6     6             6              6        6
...             ...      ...   ...           ...            ...      ...
2019 10         969      969   969           969            969      969
     11        1047     1047  1047          1047           1047     1047
     12        1297     1297  1297          1297           1297     1297
2020 1         2600     2600  2600          2600           2600     2600
     2          603      603   603           603            603      603

           tweet_source user_screenname user_name location user_description  \
                  count           count     count    count            count
year month
2012 12               6               6         6        6                0
2013 1               21              21        21       21                0
     2                5               5         5        5                0
     11               7               7         7        0                7
     12               6               6         6        0                6
...                 ...             ...       ...      ...              ...
2019 10             969             969       969      786              951
     11            1047            1047      1047      879             1031
     12            1297            1297      1297     1034             1163
2020 1             2600            2600      2600     2054             2392
     2              603             603       603      505              533

           user_followers user_friends user_create_account tweet_date  \
                    count        count               count      count
year month
2012 12                 6            6                   6          6
2013 1                 21           21                  21         21
     2                  5            5                   5          5
     11                 7            7                   7          7
     12                 6            6                   6          6
...                   ...          ...                 ...        ...
2019 10               969          969                 969        969
     11              1047         1047                1047       1047
     12              1297         1297                1297       1297
2020 1               2600         2600                2600       2600
     2                603          603                 603        603

           tweet_time
                count
year month
2012 12             6
2013 1             21
     2              5
     11             7
     12             6
...               ...
2019 10           969
     11          1047
     12          1297
2020 1           2600
     2            603

[69 rows x 16 columns]